repos:
  # Formatting
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        args:
          - --line-length=99

  # Sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
        args:
          - --profile=black

  # Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args:
          - --fix=false
          - --output-format=grouped
          - --line-length=99